### PR TITLE
change tabIndex to allowable prop

### PR DESCRIPTION
**Pull request by stevenmusumeche**

### CODE REVIEW

**Comment by ahutchings** [comment]
This change in react-virtualized appears to relax the tabIndex requirements to allow null: https://github.com/bvaughn/react-virtualized/pull/818. It has been merged in but not released yet.

It may be worth waiting for (or requesting) a react-virtualized release so we can avoid making the categories container focusable by giving it a tabIndex of 0.

The Emoji tabIndex change appears to be required regardless since the react-virtualized Grid expects a number.

**Comment by bvaughn** [comment]
As mentioned on the issue you referenced, the fix for this was included in the [9.11.0 release](https://github.com/bvaughn/react-virtualized/blob/master/CHANGELOG.md#9110) this morning.

**Comment by stevenmusumeche** [comment]
@ahutchings I've updated my PR to back out the previous changes and update the version of react-virtualized used.

**Comment by ahutchings** [comment]
Let's close this as resolved since no changes are needed in the emojione-picker codebase. The react-virtualized bump should be picked up in any consuming app automatically since it's in the allowed version range in package.json.

**Comment by stevenmusumeche** [comment]
👍

**Pull request closed without merging**
